#!/bin/bash

i=0

while [ $i -le 20 ]; do
	echo $i
	if [ $i == 4 ]; then
		echo "bad luck china"
	elif [ $i == 9 ]; then
		echo "bad luck Japan"
	elif [ $i == 17 ]; then
		echo "bad luck Italy"
	fi
	((i++))
done	
