#!/usr/bin/env bash
#clock display 12:59, displays hours 1-12 and minutes 1-59

hour=0

while [ $hour -lt 13 ]; do
	echo "Hour: $hour"
	min=1
	while [ $min -lt 60 ]; do
		echo $min
		min=$((min+=1))
	done
	((hour++))
done
